### ISSUE TITLE
Informative: Ubuntu 14.04 installation

### ISSUE THREAD

**Issue by MarkPfennig** [bitpay/insight-api#141]
Some of the npm modules required by insight-api are not configured to support ubuntu 14.04 upon download. To resolve the issue and install cleanly take the following steps:

    apt-get install nodejs npm nodejs-legacy
    cd insight-api
    npm install

If you have already tried and failed to get it working due to gyp issues, let's first clarify that Python 2.6 is not required, the default 2.7 will work fine.

To cleanly install insight-api when you have already taken some steps to try and get it set up, do the following:

    apt-get install nodejs-legacy
    cd insight-api
    npm cache clear
    rm -rf ./node_modules
    git pull
    npm install

This will remove all npm modules and reinstall them, after first providing legacy support to call `node` on the command line in addition to `nodejs` which the gyp module requires.

I hope that helps anybody experiencing issues setting up insight-api.

Thank you to BitPay for this wonderful application.

**Comment by braydonf** [comment]
This is outdated with the latest release of [bitcore](https://github.com/bitpay/bitcore), [bitcore-node](https://github.com/bitpay/bitcore-node) and insight v0.3.0. However support with the nodejs package doesn't currently work since event the latest versions of Ubuntu include v0.10.25. If needed, we can resolve with: https://github.com/bitpay/bitcore-node/issues/350

**Comment by braydonf** [comment]
You can also see the details on https://bitcore.io/guides/full-node for running with Ubuntu 14.04 with nvm.
