### ISSUE TITLE
Get all non empty bitcoin addresses

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [bitpay/insight-api#252]
Hi there,
I want to get a total count of all addresses in the blockchain (excluding non null 0 balance). Do I traverse the TX leveldb table?

**Comment by bitcoinsSG** [comment]
I have an extractor, but it does not work with the new insight-api because of change in data format. I'll look into updating it soon, but if you're running the older version you may want to give it a try.
https://github.com/bitcoinsSG/py-bitcoin-address-extractor-f-i-a

**Comment by braydonf** [comment]
This is an excellent case for writing a customized service for Bitcore, at each block, you could calculate totals and record to the database. Here is a getting started guide: https://bitcore.io/guides/service-development You can then expose a few HTTP endpoints to query the data.

**Comment by bitcoinsSG** [comment]
would this be a reasonably efficient way to parse out just UTXO set? wondering whether a block parser that reads the files directly (whether insight or Bitcoin) would be more elegant. BTW, is there any documentation on changes in the way insight stores data in leveldd files?

**Comment by braydonf** [comment]
The best way to get the UTXO set may be to create custom bindings to bitcoind to get that information, since pay-to-pubkey and pay-to-script-hash are not the only type of spendable output.

FYI: Reading the files directly is what a `blockHandler` method of a service is receiving as input: https://github.com/bitpay/bitcore-node/blob/master/lib/services/address/index.js#L433 And will handle reorgs by also removing information from the database (e.g. `del` instead of a `put` operation type).

There isn't any detailed documentation about the format of the leveldb database in bitcore-node (and the address index used for Insight), and would require reading the source. Here is a general overview though:

The address service has three indexes:
```js
AddressService.PREFIXES = {
  OUTPUTS: new Buffer('02', 'hex'), // Query outputs by address and/or height
  SPENTS: new Buffer('03', 'hex'), // Query inputs by address and/or height
  SPENTSMAP: new Buffer('05', 'hex') // Get the input that spends an output
};
```
https://github.com/bitpay/bitcore-node/blob/master/lib/services/address/index.js

The database service keeps two indexes:
```js
DB.PREFIXES = {
  BLOCKS: new Buffer('01', 'hex'), // To be able to query by block timestamp
  TIP: new Buffer('04', 'hex') // The latest block hash
};
```
https://github.com/bitpay/bitcore-node/blob/master/lib/services/db.js

**Comment by braydonf** [comment]
Above description is now outdated, this may need a custom RPC method in bitcoin.
