### ISSUE TITLE
BIP32/XPUB support

### ISSUE THREAD

**Issue by prusnak** [bitpay/insight-api#288]
I would love to see BIP32/XPUB support in Insight, so one could achieve similar functionality to this:

https://blockchain.info/xpub/xpub6CUGRUonZSQ4TWtTMmzXdrXDtypWKiKrhko4egpiMZbpiaQL2jkwSB1icqYh2cfDfVxdx4df189oLKnC5fSwqPfgyP3hooxujYzAu3fDVmz

**Comment by vertoe** [comment]
oh, crossposted this here too https://github.com/bitpay/insight/issues/597

**Comment by vertoe** [comment]
btw the link in OP is a special bip44 wallet.

**Comment by will123195** [comment]
+1

**Comment by braydonf** [comment]
You would need to know the xpubkey in advance, are do a more expensive query to derive addresses, and build a new index. Likely best for a wallet service that will know this information in advance that can query insight for address info.

**Comment by dabura667** [comment]
Very expensive...... and not too useful to most people...

It looks like blockchain.info is caching xpubs tx data (I just entered an xpub I have never put in there and it took forever... then I did it again and it was near instant)

Due to privacy implications (suddenly insight's db would be home to lots of privacy sensitive data) I would say no.

-1

**Comment by prusnak** [comment]
> Very expensive......

Agree.

> and not too useful to most people...

Disagree. This is exactly what most people implementing web HD wallets are looking for.

> Due to privacy implications (suddenly insight's db would be home to lots of privacy sensitive data) I would say no.

This is also debatable. There is really not a big difference when clients sends all its addresses in a request (and it needs to do that to learn the balance) or an XPUB.

**Comment by dabura667** [comment]
> most people implementing web HD wallets

aka not most people... (insight is not only for developers)

> There is really not a big difference when clients sends all its addresses in a request (and it needs to do that to learn the balance) or an XPUB.

The difference is that xpubs are never exposed in the blockchain, whereas addresses are.

Since insight already has all addresses indexed in the DB, there is no need to hold that data for long (whether insight is spying or not is a different story, but I believe they don't)

However, if they support xpub, they will likely need to do some caching for performance sake, which means now they have a list of all the xpubs of all the people who have queried them in a time period...

More incentive to hack any given insight instance. xpubs are like little packages of joy to someone who wants to spy on someone. Plus, if I query bitpay's insight once with my set of 50 addresses, they can not track me after that, if I query with xpub, they could track my wallet forever. (not saying they would)

**Comment by prusnak** [comment]
> aka not most people... (insight is not only for developers)

It really depends where you want to see Insight in a few years. Is it a service that has one instance running at Bitpay and is used just by the users? Or is it a useful building block of infrastructure for other Bitcoin companies?

I agree with the rest.

**Comment by dabura667** [comment]
I think xpubs should stay on the device with the xprvs wherever possible... only generate addresses for batch querying.

However, I agree xpub caching would be useful for enterprise where the end user already must trust the server adminning company

**Comment by chris-belcher** [comment]
xpub extended keys could be posted publicly as a way to collect donations. This avoids address reuse.

There's no tool that I know of that can quickly tell you the next unused bitcoin address from a xpub key.

**Comment by gabegattis** [comment]
We are not going to add this to insight-api right now. The feature may be useful, but it has performance problems and is best done by other systems.

[BWS](https://github.com/bitpay/bitcore-wallet-service) already implements something like this for supporting Copay wallets, but visibility is limited to the individual wallet.

If/when [bwdb](https://github.com/bitpay/bwdb) supports xpub in the future, we might could add it to insight, but we would have to be careful about the privacy implications. I feel like it is best for this info to be limited in visibility to a single wallet or something that would be run be individuals who need the info, and not on the main production insight.

If you do need xpub support, try creating a wallet in BWS and querying it directly using [BWC](https://github.com/bitpay/bitcore-wallet-client).
